{"name": "Verificar que se muestra una alerta cuando no se proporciona el nombre de usuario", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Your username or password is incorrect!'\nActual value: \n            Your username is invalid!\n            ×\n           \nCall log:\n  - Expect \"to_contain_text\" with timeout 5000ms\n  - waiting for locator(\"#flash.error\")\n    9 × locator resolved to <div id=\"flash\" data-alert=\"\" class=\"flash error\">…</div>\n      - unexpected value \"\n            Your username is invalid!\n            ×\n          \"\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/login_steps.py\", line 43, in step_impl\n    expect(context.page.locator(context.login_page.error_message)).to_contain_text(message)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/sync_api/_generated.py\", line 19172, in to_contain_text\n    self._sync(\n    ~~~~~~~~~~^\n        self._impl_obj.to_contain_text(\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<4 lines>...\n        )\n        ^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/_impl/_assertions.py\", line 205, in to_contain_text\n    await self._expect_impl(\n    ...<9 lines>...\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/_impl/_assertions.py\", line 75, in _expect_impl\n    raise AssertionError(\n        f\"{out_message}\\nActual value: {actual} {format_call_log(result.get('log'))}\"\n    )\n"}, "steps": [{"name": "Given que estoy en la página de inicio de sesión", "status": "passed", "start": 1751751087922, "stop": 1751751088550}, {"name": "When introduzco solo la contraseña", "status": "passed", "start": 1751751088550, "stop": 1751751088612}, {"name": "And hago clic en el botón de Login", "status": "passed", "start": 1751751088613, "stop": 1751751088777}, {"name": "Then debería ver un mensaje de error \"Your username or password is incorrect!\"", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Your username or password is incorrect!'\nActual value: \n            Your username is invalid!\n            ×\n           \nCall log:\n  - Expect \"to_contain_text\" with timeout 5000ms\n  - waiting for locator(\"#flash.error\")\n    9 × locator resolved to <div id=\"flash\" data-alert=\"\" class=\"flash error\">…</div>\n      - unexpected value \"\n            Your username is invalid!\n            ×\n          \"\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/login_steps.py\", line 43, in step_impl\n    expect(context.page.locator(context.login_page.error_message)).to_contain_text(message)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/sync_api/_generated.py\", line 19172, in to_contain_text\n    self._sync(\n    ~~~~~~~~~~^\n        self._impl_obj.to_contain_text(\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<4 lines>...\n        )\n        ^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/_impl/_assertions.py\", line 205, in to_contain_text\n    await self._expect_impl(\n    ...<9 lines>...\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/playwright/_impl/_assertions.py\", line 75, in _expect_impl\n    raise AssertionError(\n        f\"{out_message}\\nActual value: {actual} {format_call_log(result.get('log'))}\"\n    )\n"}, "start": 1751751088777, "stop": 1751751093787}], "attachments": [{"name": "Failure Screenshot", "source": "fb341feb-c851-44e6-8672-c07624198c8c-attachment.png", "type": "image/png"}], "start": 1751751087601, "stop": 1751751093886, "uuid": "2c59641d-bc2c-457d-ba8e-fdeae1d841ae", "historyId": "283c42ba905eec337f5ed9fc14cb49b9", "fullName": "Funcionalidad de Inicio de Sesión de Usuario: Verificar que se muestra una alerta cuando no se proporciona el nombre de usuario", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login_missing_username"}, {"name": "feature", "value": "Funcionalidad de Inicio de Sesión de Usuario"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}